// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	dto "git.garena.com/sea-labs-id/batch-05/assignment-golang-backend/dto"
	entity "git.garena.com/sea-labs-id/batch-05/assignment-golang-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// GetTransactions provides a mock function with given fields: _a0, _a1
func (_m *TransactionUsecase) GetTransactions(_a0 uint, _a1 entity.TransactionParams) ([]*entity.Transaction, int64, int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*entity.Transaction
	if rf, ok := ret.Get(0).(func(uint, entity.TransactionParams) []*entity.Transaction); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Transaction)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(uint, entity.TransactionParams) int64); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(uint, entity.TransactionParams) int); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(uint, entity.TransactionParams) error); ok {
		r3 = rf(_a0, _a1)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// TopUp provides a mock function with given fields: req, walletId
func (_m *TransactionUsecase) TopUp(req dto.TopUpRequest, walletId uint) (*entity.Transaction, error) {
	ret := _m.Called(req, walletId)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(dto.TopUpRequest, uint) *entity.Transaction); ok {
		r0 = rf(req, walletId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.TopUpRequest, uint) error); ok {
		r1 = rf(req, walletId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: req, walletId
func (_m *TransactionUsecase) Transfer(req dto.TransferRequest, walletId uint) (*entity.Transaction, error) {
	ret := _m.Called(req, walletId)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(dto.TransferRequest, uint) *entity.Transaction); ok {
		r0 = rf(req, walletId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.TransferRequest, uint) error); ok {
		r1 = rf(req, walletId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionUsecase(t mockConstructorTestingTNewTransactionUsecase) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
