// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	dto "git.garena.com/sea-labs-id/batch-05/assignment-golang-backend/dto"
	entity "git.garena.com/sea-labs-id/batch-05/assignment-golang-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthUtil is an autogenerated mock type for the AuthUtil type
type AuthUtil struct {
	mock.Mock
}

// ComparePassword provides a mock function with given fields: hashedPwd, inputPwd
func (_m *AuthUtil) ComparePassword(hashedPwd string, inputPwd string) bool {
	ret := _m.Called(hashedPwd, inputPwd)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedPwd, inputPwd)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GenerateAccessToken provides a mock function with given fields: req
func (_m *AuthUtil) GenerateAccessToken(req entity.User) dto.LoginResponse {
	ret := _m.Called(req)

	var r0 dto.LoginResponse
	if rf, ok := ret.Get(0).(func(entity.User) dto.LoginResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(dto.LoginResponse)
	}

	return r0
}

// HashAndSalt provides a mock function with given fields: pwd
func (_m *AuthUtil) HashAndSalt(pwd string) string {
	ret := _m.Called(pwd)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(pwd)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewAuthUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthUtil creates a new instance of AuthUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthUtil(t mockConstructorTestingTNewAuthUtil) *AuthUtil {
	mock := &AuthUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
